Add graphing bounds labels
frontrowed/graphy pull request #24
Opened 2020-01-29 17:50 UTC by halogenandtoast

When `showBoundingLabels` is true, the graph will render like this:

<img width="791" alt="Screen Shot 2020-01-29 at 11 49 45" src="https://user-images.githubusercontent.com/201288/73382648-86f13c80-428d-11ea-82a9-d72b8aa94b28.png">

2020-01-29 18:45 UTC, joris974 requested changes

2020-01-29 18:45 UTC, joris974 commented on src/helpers/paper-util.js
> +const createTick = function(point: PointT, axis: string): any {
could the `axis` be an enum `x` | `y`?

2020-01-29 18:45 UTC, joris974 commented on src/helpers/paper-util.js
> +  // rect.translate([-Math.abs(rect.bounds.topRight.x - rect.bounds.topLeft.x) / 2, -Math.abs(rect.bounds.bottomLeft - rect.bounds.topLeft) / 2])
remove comment

2020-01-29 18:45 UTC, joris974 commented on src/helpers/paper-util.js
> +const createLabel = function(point: PointT, content: string, anchor: string): any {
`anchor ` can be an enum as well

2020-01-29 18:46 UTC, joris974 commented
Great! Can we have different type of graph where the origin is in the center?

2020-01-29 18:59 UTC, halogenandtoast commented
@joris974 I checked with product and they mentioned there are no graphs where the origin is not the center.

2020-01-29 19:06 UTC, joris974 approved these changes

2020-01-29 20:17 UTC, merged

2020-01-29 23:30 UTC, cdparks commented
I'm seeing about 300 graphing questions with a non-center origin:

```sql
select
  id,
  ( cast(extra#>>'{graph-grid-lower-bound,x}' as double precision)
  + cast(extra#>>'{graph-grid-upper-bound,x}' as double precision)
  ) / 2.0 as origin_x,
  ( cast(extra#>>'{graph-grid-lower-bound,y}' as double precision)
  + cast(extra#>>'{graph-grid-upper-bound,y}' as double precision)
  ) / 2.0 as origin_y
from
  math_questions
inner join
  math_question_content_en
  ON math_question_content_en.math_question_id = math_questions.id
where
  answer_type like 'graph%'
  and (
    (
      ( cast(extra#>>'{graph-grid-lower-bound,x}' as double precision)
      + cast(extra#>>'{graph-grid-upper-bound,x}' as double precision)
      ) / 2.0 <> 0
    ) or
    (
      ( cast(extra#>>'{graph-grid-lower-bound,y}' as double precision)
      + cast(extra#>>'{graph-grid-upper-bound,y}' as double precision)
      ) / 2.0 <> 0
    )
  );
```

<details>
  <summary>
    Click here to expand results
  </summary>

<br>

|`id`|`origin_x`|`origin_y` |
|--- | --- | --- |
|`12a083d45c7a`|0|6.5|
|`7027bf67bf5f`|0|-5|
|`c81f2c2c4e97`|5|10|
|`2b9552e9d304`|0|2.5|
|`91caaab0bc8e`|4|5|
|`4397a1667228`|4|10|
|`d54b2e79a5bf`|4|4|
|`eb1b15ae6365`|4|14|
|`a375400f83f1`|4|7.5|
|`1ce1ffc6da1f`|4|14|
|`c09e40951678`|3|65|
|`dcc58ebc2630`|6.5|6.5|
|`d3e474bfdd61`|4|9|
|`9778498b7932`|4|-11|
|`b8408ff104e8`|4|6.5|
|`aa6271aba001`|6.5|6.5|
|`cd912d1fc57d`|4|10|
|`6cd1bbeceb89`|4|6.5|
|`38fd7b33966e`|4|0|
|`0d160132bb35`|2.5|-150|
|`75d32e5f5ed9`|2.5|-5|
|`5bd744dc4ec7`|4|9|
|`b5a110082df2`|2.5|120|
|`57bf137d4418`|2.5|300|
|`d725f72b64ec`|2.5|65|
|`604d81fc45fb`|2.5|5|
|`ed694b2a69ef`|2.5|72.5|
|`b9e28ae0c60b`|2.5|1500|
|`74c1b0273f2b`|2.5|70|
|`6181906be1d3`|2.5|1875|
|`8513a9904144`|2.5|112.5|
|`0dbc54d8c1d5`|2.5|21|
|`8c1a9eb7dd06`|2.5|10|
|`4ad98478a159`|2.5|20|
|`5244d94f7d5e`|2.5|120|
|`d431d7a9e67d`|2.5|300|
|`62cda1bb99a5`|2.5|70|
|`b4472a616e01`|2.5|5|
|`50431786e7ab`|2.5|55|
|`4489ef0cf284`|2.5|1500|
|`1d7b01199863`|2.5|70|
|`9411a7149376`|2.5|1875|
|`e03057836d89`|2.5|100|
|`8b870a3c64dc`|2.5|21|
|`b4bd445dfbdd`|2.5|10|
|`0bf614c48490`|2.5|20|
|`cc100871c7a1`|2|35|
|`8e120491057e`|2|20|
|`0d333cf3d8e5`|2|13.5|
|`e4aabfdbc06b`|0|2.5|
|`ae4eff89b232`|2|42.5|
|`53f20370b59a`|2|10.5|
|`84079721deca`|2|18|
|`c653cbbea923`|2|28|
|`a6a6534deab0`|2|18|
|`5bc35df8fc32`|2|28|
|`d54ad71366a7`|2|22.5|
|`f956ce6f561f`|2|12.5|
|`4a33d00cebec`|2|35|
|`39e418871f1e`|2|20|
|`c93b4fa4cfe4`|2|13.5|
|`03147fac6729`|0|2.5|
|`a42cd0654878`|2|42.5|
|`23603e14f506`|2|10.5|
|`bbb61394bfda`|2|18|
|`c5e179f171fd`|2|28|
|`6871aaca062d`|2|18|
|`bebb6d6e4417`|2|28|
|`577ca5cdcde0`|2|22.5|
|`f4ff2c47aae4`|2|12.5|
|`dbcbbcba0014`|33|72.5|
|`eef1bde097bd`|33|82.5|
|`19e6444e1226`|32|72.5|
|`cc409d16825c`|38|77.5|
|`e5a57e5fd4e5`|35|87.5|
|`acc2c18b061b`|8|45|
|`048501b5ecdd`|10|45|
|`c8d10e80540d`|8|45|
|`925e9bd8f329`|6|45|
|`993c1a3adef5`|6|45|
|`a3646711a5c1`|4|10|
|`822511e41ca4`|60|110|
|`776a3baf67b6`|55|110|
|`569a6f688e29`|55|120|
|`ecdbc6c81a8c`|55|130|
|`1661f4f8776b`|65|142.5|
|`28cdae43af84`|15|45|
|`c4514b7ecb77`|10|45|
|`fdc0642decc1`|8|45|
|`ccab81a9dd7f`|8|50|
|`fced4f0d0d73`|8|50|
|`758ff4b03e55`|2.5|0|
|`6a4ec9921839`|2.5|0|
|`438fd938511f`|2.5|0|
|`47df3652868c`|2.5|0|
|`63f227118ff2`|2.5|0|
|`714ca94c0524`|2.5|0|
|`1913bb6a434c`|2.5|0|
|`d9f711575776`|2.5|0|
|`0d77707e93ae`|2.5|0|
|`58468f357901`|2.5|0|
|`3c1bdd3a0d85`|2.5|0|
|`9f8eaa6a10f2`|2.5|0|
|`3c66647f94e0`|2.5|0|
|`b45fd2a2820f`|2.5|0|
|`da7e38231bd1`|2.5|0|
|`d9d351f3d3bb`|0|5|
|`1fa8c08b7c14`|0|5|
|`fcc83faac77c`|0|16.5|
|`aaeca5524429`|0|22|
|`779228bf6750`|0|22.5|
|`778200f67f5c`|0|17.5|
|`ac12cba70c5c`|0|25|
|`2e85f7e76757`|0|25|
|`88c28770f2ea`|0|32.5|
|`3212364b46f6`|0|45|
|`7558772b220d`|0|45|
|`cb9c4696f8aa`|0|50|
|`30d0ba67ae50`|0|6|
|`5c1ac0432e30`|0|22.5|
|`57e75abfed4f`|0|22.5|
|`2beedde75640`|0|47.5|
|`b72c61d538e9`|0|47.5|
|`c41d0522f6fd`|0|47.5|
|`44a27842900a`|0|100|
|`00ab39a02a49`|0|112.5|
|`27044dad3c9f`|0|140|
|`160f8ce84550`|0|200|
|`20f953253967`|0|240|
|`5200ab4e3f4b`|0|337.5|
|`e82acdee6e3f`|4|9|
|`3ea5873e0bdf`|4|9|
|`622b6ca37d05`|4|9|
|`ca6127a9734f`|4|9|
|`9233a9938457`|4|9|
|`658f77f9e1da`|4|9|
|`094d2badb9ab`|4|9|
|`3fba4d40b119`|4|9|
|`df1a68feac46`|4|9|
|`9ebc217a0477`|4|9|
|`099858a4610c`|4|9|
|`d04e83957240`|4|9|
|`93f245b6973e`|4|9|
|`2b91e7539b16`|4|9|
|`ffc618095155`|4|9|
|`cc6043219dc3`|4|9|
|`43dbf465ad21`|4|9|
|`2d260f21d968`|4|9|
|`465e03961fe5`|4|9|
|`477bb5880957`|4|9|
|`b17560451161`|4|9|
|`c07a28646853`|4|9|
|`1889e67d54e0`|4|9|
|`94ea0bc8139e`|4|9|
|`63758b1badcf`|4|9|
|`3613748b6a51`|4|9|
|`937621605396`|4|9|
|`ff07f1b224ec`|4|9|
|`e16b0cfc443c`|4|9|
|`401f22e6d345`|4|9|
|`298f289772dd`|4|9|
|`23a13a15b7e7`|4|9|
|`d8b830cd6225`|4|17|
|`39890447e6e6`|4|17|
|`5daf57796291`|4|22.5|
|`cb406bce66a6`|4|17|
|`981b66cf9895`|0|10|
|`c8ea1ee55cba`|0|4.5|
|`6503da09f6c4`|2|-7|
|`0c114735385d`|5|-4|
|`71a1cfc15c51`|0|4|
|`660bea9cba9a`|0|3|
|`401a7ac95236`|0|2|
|`2005763b316a`|0|4|
|`1c1abec4cf08`|0|23|
|`0ebbebb05b88`|0|12|
|`0b0617d87d2b`|10|-15|
|`033b2ebf5474`|0|7.5|
|`7d2a48e2d8c2`|0|5|
|`ac774bc9da81`|2|9|
|`fa9011771193`|2|9|
|`603d4cb102bf`|2|9|
|`4edfce795dd7`|2|9|
|`dc13f7d3a4f4`|2|9|
|`ce9fa89892cb`|2|9|
|`1d7a94c04d9b`|2|0|
|`6173f8189ade`|2|0|
|`40181e82dcce`|2|0|
|`b86e43d59135`|2|0|
|`2ce04bccaed6`|2|0|
|`1e3edaa82463`|2|0|
|`132274628936`|0|5|
|`3293dd920052`|5|100|
|`9367e34be26c`|5|200|
|`e53de393b909`|5|100|
|`d497b88e4f55`|5|7.5|
|`40f39ee9873d`|5|75|
|`92af79396fb8`|5|1700|
|`c1101aac4341`|5|6|
|`f6afc3730ecd`|5|100|
|`e57e0f81a860`|5|3000|
|`859b76b0e4b5`|5|150|
|`cd381841e96a`|5|90|
|`c691b3e1ed6c`|5|15|
|`224728603001`|2|38|
|`4f674d5804f4`|1|18|
|`d74c1f7f737a`|1|47.5|
|`aa382d9d5c40`|1|145|
|`f32d886d7f9f`|2|43.5|
|`1efdf0207e1e`|1.5|87|
|`ba43d8232f7d`|1|66.5|
|`973a44660bd8`|1|130.5|
|`0a6857cfdb5a`|1.5|45|
|`db22cb90e15d`|1|67.5|
|`ee142d42c719`|1.5|104.5|
|`223417b5a1d1`|1|58|
|`ee775c47d77d`|1|28.5|
|`355c250dcb88`|1.5|72.5|
|`f03f78782c4d`|2|45|
|`1eb92bdacc84`|1.5|52|
|`83f241b4447b`|3.5|35|
|`9fe2b392dfff`|3.5|35|
|`0d7e2ce67b78`|3.5|35|
|`895b2892f827`|3.5|145|
|`f0b6391eac4a`|3.5|25.5|
|`c4c363dd1ba2`|3.5|15|
|`4a8be1a36570`|3.5|24|
|`97b9a396f2df`|3.5|35|
|`b2c86b7cd006`|3.5|36|
|`25a2370fe9c8`|3.5|55|
|`a5b32a6bfc0d`|3.5|85.5|
|`b0aa77db12f4`|3.5|45|
|`1e69c6e688db`|0|48|
|`f946781a1093`|0|96|
|`de8abd6cea2d`|0|66.5|
|`3b79ae8f75a8`|0|87|
|`39f569c239d3`|0|97.5|
|`8ba90f984b67`|0|48|
|`c563b368df1b`|0|14|
|`ff8672140d91`|0|12.5|
|`ad443f9560c6`|0|14|
|`c6ebc7692ada`|0|12.5|
|`109a16b47fce`|0|12.5|
|`671d416fd1a6`|0|12.5|
|`fc5f9a1a2bc1`|4|8|
|`8e4f7b69cc07`|0|10|
|`790bfefff77d`|0|10|
|`970aef72db2e`|0|10|
|`3d5b87584695`|0|10|
|`f6992ae49d05`|0|9|
|`0bdad44c4a72`|0|1.5|
|`981e08e29cb5`|0|1.5|
|`8e7788d57044`|3.5|4.5|
|`2a11cd163737`|3|8|
|`086203668fd3`|2|5|
|`ff2a914eef4e`|-12.5|17.5|
|`6977eaf33aa2`|0|53|
|`57b03199b9e1`|0|-1|
|`ed72f0b423a5`|5|10|
|`873bc052ad9e`|0|17.5|
|`4656ffbf07d4`|0|1.5|
|`c62ec95df070`|0|1.5|
|`c498d83c9079`|3.5|4.5|
|`38d3b8c9dfad`|3|8|
|`efa874a38be3`|2|5|
|`5e73707e71f4`|-20|30|
|`295c9113e5b6`|0|50|
|`60ffd621efbb`|0|-1|
|`298776e12147`|7.5|10|
|`553f5703634c`|0|15|
|`055273a78ec5`|2.5|9.5|
|`d76269b3fd50`|2.5|4.5|
|`a7fb89e5db69`|2.5|9.5|
|`1e2c1c2e499e`|2.5|9.5|
|`badaa59eaa57`|2.5|9.5|
|`d2e9493f7402`|2.5|4.5|
|`a22daa057a4a`|2.5|4.5|
|`240d71e10cf4`|2.5|4.5|
|`2ef063dd8e18`|2.5|9.5|
|`bd4046cbc7b1`|2.5|4.5|
|`ef0aa45f8d1d`|2.5|9.5|
|`a0181e1140e6`|2.5|9.5|
|`69882f5c0b7b`|2.5|4.5|
|`ba407c090c94`|2.5|4.5|
|`aa9b7a815212`|2.5|9.5|
|`cebe62342b66`|2.5|4.5|
|`0eda2cbe3151`|2.5|4.5|
|`d3e894a97806`|2.5|9.5|
|`6d152d313136`|2.5|4.5|
|`957ea380c5ab`|2.5|9.5|
|`a1772b3be1e6`|2.5|4.5|
|`6fdc3711fed5`|2.5|9.5|
|`fc7bfadd6fcd`|2.5|4.5|
|`029dc6d3a479`|2.5|9.5|
|`3adb3c7b6f0c`|3.5|2.5|
|`4445df1ced5e`|3.5|3|
|`7df2995bc940`|5|0|
|`5b08792bf969`|0|5|
|`434c3d02c1cb`|0|-5|
|`5c1bd2057b43`|0|10|
|`fa336beb29f4`|0|10|
|`04c09c9df6e2`|0|-5|
|`96d9cd80 [...]

2020-01-29 23:33 UTC, cdparks commented
I guess the logical origin for these is still `(0, 0)`, but it's not always drawn to be in the graph's physical center.

2020-01-29 23:35 UTC, cdparks commented
From the code, I don't see why that would be a problem, unless you just wanted to see what it looks like, @joris974

2020-01-30 00:37 UTC, halogenandtoast commented
@cdparks the non-origin thing wasn’t an issue. What might need to be added is a way to account for the view matrix as the text position and size doesn’t account for the graph being different sizes.